FROM mcr.microsoft.com/devcontainers/cpp:1.0.0-buster
RUN sed -i s/deb.debian.org/archive.debian.org/g /etc/apt/sources.list
RUN sed -i s/security.debian.org/archive.debian.org/g /etc/apt/sources.list
