@startuml
Client -> NormInstance : OpenDebugLog(filename)
NormInstance -> NormApi : NormOpenDebugLog(_handle, filename)
NormInstance <- NormApi : success
alt success == True
else success == false
    NormInstance -> IOException : throw new ("Failed to open debug log")
end
@enduml