name: ".NET Publish"

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/dotnet

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: Package .NET
      uses: devcontainers/ci@v0.3
      with:
        push: never
        runCmd: | 
          cd ./src/dotnet
          chmod 755 *.sh
          ./pack-linux-x64.sh
    - name: Check workspace contents
      run: ls /home/runner -R
      working-directory: .
