name: ".NET Publish"

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/dotnet

    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: Package .NET
      uses: devcontainers/ci@v0.3
      with:
        push: never
        runCmd: | 
          cd ./src/dotnet
          chmod 755 *.sh
          ./pack-linux-x64.sh
          find ./src -name \*linux*.nupkg -exec cp {} $GITHUB_WORKSPACE \;
    - name: Check workspace contents
      run: ls
      working-directory: .
