name: .NET

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      packages: write
    defaults:
      run:
        working-directory: ./src/dotnet

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: Setup Python
      uses: actions/setup-python@v3.1.4
      with:
        python-version: 3.x
    - name: Build NORM
      run: ./waf
      working-directory: .
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore /property:Configuration=Release
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Package .NET
      uses: devcontainers/ci@v0.3
      with:
        imageName: ghcr.io/${{ github.repository_owner }}/norm-devcontainer
        cacheFrom: ghcr.io/${{ github.repository_owner }}/norm-devcontainer
        push: never
        runCmd: | 
          cd ./src/dotnet
          chmod 755 *.sh
          ./pack-linux-x64.sh
