name: ".NET Publish"

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/dotnet

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: Package .NET
      uses: devcontainers/ci@v0.3
      with:
        push: never
        runCmd: | 
          cd ./src/dotnet
          chmod 755 *.sh
          ./pack-linux-x64.sh
    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Publish .NET
      run: |
        package=$(find /home/runner/work -type f -name "*linux-x64*.nupkg")
        dotnet nuget push "$package"
